In [2]:
import numpy as np
a = np.arange(1, 10, 1)

In [3]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b=a[0:2, 0:3]
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b=a[0, :] # 첫번째 행 출력
print(b)

[1 2 3]


In [11]:
c = (3,4) #tuple 은 데이터 수정 불가
print(c)
print(c[0])

d = [3,4] #list
print(d)
print(d[0]) #접근은 똑같아

e = { "item1":3, "item2":4 } #dictionary
print(e)
print(e["item1"])

(3, 4)
3
[3, 4]
3
{'item1': 3, 'item2': 4}
3


In [14]:
f = {0:3, 1:4}
print(f[0])  #key value=0인 걸

3
