# Deep Learning
머신러닝 교과서 chap.2, 12~15
케라스딥러닝 chap.1 머신러닝 이론 개괄

### 인공 지능과 머신 러닝, 딥 러닝의 차이점
#### 인공 지능
* 인공 지능 - 1956년 미국 다트머스 대학에 있던 존 매카시 교수가 개최한 다트머스 회의에서 처음 등장
* 2015년 이후 신속하고 강력한 병렬 처리 성능을 제공하는 GPU의 도입으로  인공지능의 성장세 가속화 - 폭발적으로 늘어나고 있는 저장 용량과 이미지, 텍스트, 매핑 데이터 등 모든 영역의 데이터가 범람하게 된 ‘빅데이터’가 인공지능의 성장세에 큰 영향을 줌
* 인간이 지닌 지적 능력을 인공적으로 구현한 것
* 기계 혹은 시스템에 의해 만들어진 지능General AI - 인간의 감각, 사고력을 지닌 채 인간처럼 생각하는 인공 지능
* Narrow AI - 소셜 미디어의 이미지 분류 서비스나 얼굴 인식 기능 등과 같이 특정 작업을 인간 이상의 능력으로 해낼 수 있는 것
* 인간의 학습능력, 추론능력, 지각능력, 자연언어 등의 이해능력을 컴퓨터 프로그래밍으로 구현한 기술
#### 머신 러닝
* 알고리즘을 이용해 데이터를 분석하고, 분석을 통해 학습하며, 학습한 내용을 기반으로 판단이나 예측을 합니다. 
* 궁극적으로는 의사 결정 기준에 대한 구체적인 지침을 소프트웨어에 직접 코딩해 넣는 것이 아닌, 대량의 데이터와 알고리즘을 통해 컴퓨터 그 자체를 ‘학습’시켜 작업 수행 방법을 익히는 것을 목표로 함
* 알고리즘 방식 - 의사 결정 트리 학습, 귀납 논리 프로그래밍, 클러스터링, 강화 학습, 베이지안(Bayesian) 네트워크 등이 포함
* 인공지능의 한 분야로서 빅데이터를 분석하고 가공해서 새로운 정보를 얻어 내거나 미래를 예측하는 기술
* 인공지능의 하위 분야
* 기계가 직접 데이터를 학습(러닝)함으로써 그 속에 숨겨진 일련의 규칙성을 찾는다
* 예] 문자인식, 음성인식, 바둑 또는 장기 등의 게임 전략, 의료 진단, 로봇개발
#### 머신 러닝 응용분야
* 클래스 분류(Classification)
* 클러스터링 – 그룹 나누기(Clustering)
* 추천(Recommendation)
* 회귀(Regression)
* 차원 축소(Dimensionality Reduction) – 특성을 유지한 상태로 고차원의 데이터를 저차원의 데이터로 변환하는 것
데이터를 시각화하거나 구조를 추출해서 용량을 줄여 계산을 빠르게 하거나 메모리를 절약할때 사용
* 초과 적합(Overfitting) – 훈련 전용 데이터가 학습돼 있지만 학습되지 않은 새로운 데이터에 대해 제대로 된 예측을 못하는 상태
#### 딥러닝(심층학습, 강화학습) 
* 여러 층을 가진  인공신경망을 이용하여 머신러닝을 수행하는 것
* 인공신경망을 넓고 다층(Deep)으로 쌓으면 딥러닝(Deep-Learning)
* 신경망을 사용해 수많은 데이터 속에서 어떤 패턴을 파악하고 이것을 통해 인간이 사물을 구분하듯이 컴퓨터가 데이터를 나누는 것 (사물이나 데이터를 군집화 하거나 분류할 때 사용)
* 데이터 자체를 컴퓨터에게 전달,  인공신경망 구조를 사용하여 데이터 전체를 학습시킨다 (인간의 뇌에서 일어나는 의사결정 과정을 모방한 인공신경망(Artificial Neural Network) 구조를 통해서 학습한다)
* 예]  컴퓨터에 개와 고양이 사진을 학습시켜 특정사진의 동물이 개인지 고양이인지 분류
일반적인 기계학습의 경우 개와 고양이의 구별되는 큰 특징들만 뽑아 컴퓨터에게 전달) 딥러닝은 개, 고양이 사진 자체를 컴퓨터가 학습하도록 하는 것
#### 인공 지능과 머신 러닝, 딥 러닝의 차이점
딥러닝 단계에서 군집화된 데이터를 분류 → 머신러닝 단계를 거쳐 학습 → 인공지능의 단계에서는 어떤 판단이나 결과를 내는 과정
#### AI의 패러다임
* 심볼릭 AI의 패러다임 - 규칙(프로그램)과 이 규칙에 따라 처리될 데이터를 입력하면 해답이 출력
* 머신 러닝 - 데이터와 데이터로부터 기대되는 해답을 입력하면 규칙이 출력
* 머신러닝은 데이터에서 통계적 구조를 찾아 그 작업을 자동화하기 위한 규칙을 만들어 냅니다. (학습)
* 머신 러닝 모델은 입력 데이터를 기반으로 기대 출력에 가깝게 만드는 유용한 표현(representation)을 학습하는 것
* 머신 러닝에서의 학습(Learning)이란 더 나은 표현을 찾는 자동화된 과정입니다.
* 모든 머신 러닝 알고리즘은 주어진 작업을 위해 데이터를 더 유용한 표현으로 바꾸는 이런 변환을 자동으로 찾습니다.
* 머신 러닝 연산 - 선형 투영(linear projection)(정보를 잃을 수 있음), 이동(translation), 비선형 연산(예를 들어 x > 0인 모든 포인트를 선택하는 것) 등
* 가설 공간(hypothesis space)이라 부르는 미리 정의된 연산의 모음들을 자세히 조사하는 것
* 머신 러닝은 가능성 있는 공간을 사전에 정의하고 피드백 신호의 도움을 받아 입력 데이터에 대한 유용한 변환을 찾는 것
#### 흰색 포인트와 검은색 포인트의 좌표 (x, y)를 입력으로 받고, 포인트가 검은색인지 흰색인지를 출력하는 알고리즘을 개발  
* 입력은 포인트의 좌표 
* 기대 출력은 포인트의 색깔
* 알고리즘의 성능을 측정하는 방법은 정확히 분류한 포인트의 비율을 사용하여 알고리즘의 성능을 측정
#### 딥러닝   
* 기본 층을 겹겹이 쌓아 올려 구성한 신경망(neural network)이라는 모델을 사용하여 표현 층을 학습
* 층 기반 표현 학습(layered representations learning) 또는 계층적 표현 학습(hierarchical representations learning)
#### 깊은 신경망(Deep Neural Network : DNN)   
* 신경망을 3개 이상 중첩


### 환경설정 및 라이브러리
#### 딥러닝 라이브러리   
* 케라스(keras)를 사용해 딥러닝을 실행시킵니다. 
* 케라스가 구동되려면 텐서플로(TensorFlow) 또는 씨아노(theano)라는 두 가지 라이브러리 중 하나가 미리 설치되어 있어야 합니다

keras 라이브러리 - Sequential() 와 Dense()   
* Sequential() - 딥러닝의 구조를 한 층 한 층 쉽게 쌓아올릴 수 있게 해 줍니다. 
* Sequential 함수를 선언하고 나서 model.add() 함수를 사용해 필요한 층을 차례로 추가합니다.
* Dense( activation=, loss=, optimizer=) 각 층이 제각각 어떤 특성을 가질지 옵션을 설정하는 역할을 합니다.
activation: 다음 층으로 어떻게 값을 넘길지 결정하는 부분(가장 많이 사용되는 relu와 sigmoid 함수)
loss: 한 번 신경망이 실행될 때마다 오차 값을 추적하는 함수
optimizer: 오차를 어떻게 줄여 나갈지 정하는 함수
* model.evaluate() - 딥러닝의 모델이 어느 정도 정확하게 예측하는지를 점검


## TensorFlow 모듈
* 구글이 공개한 대규모 숫자 계산을 해주는  머신러닝 및 딥러닝 전문 라이브러리
* Tensor는 다차원 행렬 계산을 의미
* 상업적인 용도로 사용할 수 있는 오픈소스(Apache 2.0)
* C++로 만들어진 라이브러리
* 파이썬을 사용해서 호출할 때 오버헤드가 거의 없는 구조로 설계
* https://www.tensorflow.org
* 이미지 처리와 음향 처리 등을 할 때는 추가적으로 이미지 처리에 특화된 OpenCV 라이브러리등과 함께 사용

In [4]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [ ]:
pip uninstall tensorflow

In [ ]:
pip install tensorflow == 1.15

#### 상수 지정

In [1]:
import tensorflow as tf
#상수 정의
a = tf.constant(1234)
b = tf.constant(5000)

#계산 정의
add_op = a+b

#세션 시작
sess = tf.Session()
res = sess.run(add_op)
print(res)

C:\Users\student\Anaconda3\envs\test\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


6234


In [2]:
import tensorflow as tf

#상수 정의
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

#계산 정의
calc1_op = a+b*c
calc2_op = (a+b)*c

#세션 시작
sess = tf.Session()
res1 = sess.run(calc1_op)
print(res1)
res2 = sess.run(calc2_op)
print(res2)

14
20


In [3]:
import tensorflow as tf

#상수 정의
a = tf.constant(100) 
b = tf.constant(50)
add_op = a+ b

#변수 v 선언하기
v = tf.Variable(0)

#세션 시작 
sess = tf.Session() 
# 변수 초기화히기
# 변수는 초기화하지 않으면 사용할 수 없다. 반드시 initialization 하여야 한다.
sess.run(tf.global_variables_initializer())

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op) #assign이 변수의 초기값을 설정하는 것

#계산식 실행
sess.run(let_op) 
print(sess.run(v))

150


#### Placeholder
* 템플릿처럼 값을 넣을 공간을 만들어두는 기능
* 데이터 플로우 그래프를 구축할 때는 값을 넣지 않고 값을 담을 수 있는 그릇만 만들어두고, 이후에 세션을 실행할 때 그릇에 값을 넣고 실행할 수 있습니다

##### 배열 갯수 고정

In [5]:
import tensorflow as tf

#placeholder 정의 - 정수 자료형 3개를 가진 배열
a = tf.placeholder(tf.int32, [3])
b = tf.constant(2)
x2_op = a*b

#세션 시작
sess = tf.Session()
#placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1,2,3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10,20,10]})
print(r2)

[2 4 6]
[20 40 20]


##### 배열 갯수 가변

In [7]:
import tensorflow as tf

#placeholder 정의( 배열의 크기를 None으로 지정)
a = tf.placeholder(tf.int32, [None])
b = tf.constant(10)
x10_op = a*b

#세션 시작 
sess = tf.Session()
# placeholder에 값 넣고 실행하기
r1 = sess.run(x10_op, feed_dict = {a:[1,2,3,4,5]})
print(r1)
r2 = sess.run(x10_op, feed_dict = {a:[10,20]})
print(r2)

[10 20 30 40 50]
[100 200]



SVM(Supprt Vector Machine)으로 BMI 판정
키의 최대값은 200cm, 몸무게의 최대값은 100kg으로 정규화
저체중(thin), 정상(normal), 비만(fat) 레이블을 one-hot-encoding [1, 0, 0], [0, 1, 0], [0, 0, 1]로 변환
소프트 맥스 회귀방법 , 오차 함수는 교차 엔트로피 사용
교차 엔트로피  - 2개의 확률 분포 사이에 정의되는 척도로서 교차 엔트로피 값이 작을 수록 정확한 값을 냄
학습 계수 0.01, 경사 하강법(steepest descent method) 사용

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기 
csv = pd.read_csv("bmi.csv")
# 데이터 정규화 
 
# 레이블을 배열로 변환하기 - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
 
# 테스트를 위한 데이터 분류 

# 데이터 플로우 그래프 구축하기 
# 플레이스홀더 선언하기
 
# 변수 선언하기 
 
# 소프트맥스 회귀 정의하기 
 
# 모델 훈련하기 
 
# 정답률 구하기
 
# 세션 시작하기
 
 
# 학습시키기
 
# 최종적인 정답률 구하기
 


In [ ]:
## 데이터플로우 그래프 구축
#플레이스홀더 선언
x = tf.placeholder(tf.float32, [None, 2])
y = tf.placeholder(tf.float32, [None, 3])
#변 수선언
W = tf.Variable(tf.zeros[2,3]) #가중치
b = tf.Variable(tf.zeros[3]) #bais
#소프트맥스 회귀 정의
y= tf.nn.softmax(tf.matmul(x,W)+b)
#모델 훈련
cross_entropy = tf.reduce_sum()

## TensorBoard
* 데이터의 흐름을 시각화하는 도구
* 로그 데이터를 저장할 폴더 준비 
* tensorbord –logdir=로그데이터 저장폴더
* Localhost:6006

In [10]:
import tensorflow as tf
# 데이터 플로우 그래프 구축하기  
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")
mul_op = a * b
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
# 세션 실행하기 
print(sess.run(mul_op))

600


In [ ]:
import tensorflow as tf
# 상수와 변수 선언하기  
a = tf.constant(100, name="a")
b = tf.constant(200, name="b")
c = tf.constant(300, name="c")
v = tf.Variable(0, name="v")
# 곱셈을 수행하는 그래프 정의하기  
calc_op = a + b * c 
assign_op = tf.assign(v, calc_op)
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
# 세션 실행하기   
sess.run(assign_op)
print(sess.run(v))

In [ ]:
# BMI 판정
import pandas as pd
import numpy as np
import tensorflow as tf

# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기
csv = pd.read_csv("bmi.csv")
# 데이터 정규화 
 
# 레이블을 배열로 변환하기
 

# 테스트를 위한 데이터 분류
 

# 플레이스홀더로 이름 붙이기
 
 


In [ ]:
# keras 이용 BMI 판정
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.callbacks import EarlyStopping
import pandas as pd, numpy as np
# BMI 데이터를 읽어 들이고 정규화하기  
 
# 몸무게와 키 데이터
 

# 레이블
 
# 훈련 전용 데이터와 테스트 전용 데이터로 나누기  
 
# 모델 구조 정의하기  
 


## 딥러닝 동작 원리
#### 선형 회귀(linear regression)   
* 단순 선형 회귀(simple linear regression)  - 하나의 x 값만으로 y 값을 설명
* 다중 선형 회귀(multiple linear regression) - 여러개의 x 값이 y 값을 설명
* 선형 회귀는  정확한 직선을 그려내는 과정으로 직선의 기울기 a 값과 y 절편 b 값을 정확히 예측해 내야 하는 것

산점도를 그려 선형인지 확인
#### 최소 제곱법(method of least squares)   
* 최소 제곱법 -  회귀 분석에서 사용되는 표준 방식
* 실험이나 관찰을 통해 얻은 데이터를 분석하여 미지의 상수를 구할 때 사용되는 공식
* 최소 제곱법을 통해 일차 함수의 기울기 a와 y 절편 b를  구할 수 있습니다.

##### 최소 제곱법 공식으로 구한 성적 예측 코딩

In [15]:
import numpy as np

x = [2,4,6,8]
y = [81,93,91,97]

mx = np.mean(x)
my = np.mean(y)
print("x의 평균값:", mx)
print("y의 평균값:", my)

divisor = sum([(mx-i)**2 for i in x]) #a 분모

def top(x,mx,y,my) : #a 분자
    d = 0
    for i in range(len(x)):
        d += (x[i] - mx) * (y[i]-my)
    return d

dividend = top(x,mx,y,my)
print("분모:", divisor)
print("분자:", dividend)

a = dividend / divisor
b = my - (mx*a)

print("기울기:",a)
print("y절편:",b)

x의 평균값: 5.0
y의 평균값: 90.5
분모: 20.0
분자: 46.0
기울기: 2.3
y절편: 79.0


#### 평균 제곱근 오차(root mean square error)   
* 딥러닝은 대부분 입력 값이 여러 개인 상황에서 이를 해결하기 위해 실행됩니다. 
* 여러 개의 입력 값을 계산할 때는 임의의 선을 그리고 난 후, 이 선이 얼마나 잘 그려졌는지를 평가하여 조금씩 수정해 가는 방법을 사용합니다.
* 가설을 하나 세운 뒤 이 값이 주어진 요건을 충족하는지 판단하여 조금씩 변화를 주고, 이 변화가 긍정적이면 오차가 최소가 될 때까지 이 과정을 계속 반복하는 방법입니다. 
* 선을 긋고 나서 수정하는 과정에서 나중에 그린 선이 먼저 그린 선보다 더 좋은지 나쁜지를 판단하는 방법이 필요합니다.
* 각 선의 오차를 계산할 수 있어야 하고, 오차가 작은 쪽으로 바꾸는 알고리즘이 필요합니다.
* 기울기가 잘못되었을 수록 직선과의 거리의 합, 즉 오차의 합도 커집니다. 
* 기울기가 무한대로 커지면 오차도 무한대로 커지는 상관관계가 있습니다. 
* 오차 = 실제 값 - 예측 값
* 오차의 합을 구할 때, 오차에 양수와 음수가 섞여 있기 때문에 오차를 단순히 더해 버리면 합이 0이 될 수도 있으므로 각 오차의 값을 제곱해 줍니다
* 평균 제곱 오차(Mean Squared Error, MSE) - 오차 합의 평균
* 평균 제곱근 오차(Root Mean Squared Error, RMSE) - 평균 제곱 오차는 각 오차를 제곱한 값을 사용하므로 대용량 데이터를 이용할 때는 오차가 커지고, 계산 속도가 느려지는 경우  제곱근을 씌워 줍니다.

선형 회귀란 임의의 직선을 그어 이에 대한 평균 제곱근 오차를 구하고, 이 값을 가장 작게 만들어 주는 a와 b 값을 찾아가는 작업입니다.

#### 평균 제곱근 오차 구현 코드

In [18]:
import numpy as np
# 기울기 a와 y 절편 b
ab = [3,76]

# x, y의 데이터 값
data = [[2,81],[4,93],[6,91],[8,97]] #data set
x = [ i[0] for i in data ]
y = [ i[1] for i in data ]

# y = ax + b에 a와 b 값을 대입하여 결과를 출력하는 함수
def predict(x):
    return ab[0]*x+ab[1]

# RMSE 함수
def rmse(p,a):
    return np.sqrt(((p-a)**2).mean())





# RMSE 함수를 각 y 값에 대입하여 최종 값을 구하는 함수
def rmse_val(predict_result,y) :
    return rmse(np.array(predict_result),np.array(y))

# 예측 값이 들어갈 빈 리스트
predict_result = []

# 모든 x 값을 한 번씩 대입하여
for i in range(len(x)):
    predict_result.append(predict(x[i]))
    print("공부한 시간 =%.f, 실제점수=%.f, 예측점수=%.f" % (x[i],y[i],predict_result[i]))

# 최종 RMSE 출력
print("rmse 최종값 :" + str(rmse_val(predict_result,y)))

공부한 시간 =2, 실제점수=81, 예측점수=82
공부한 시간 =4, 실제점수=93, 예측점수=88
공부한 시간 =6, 실제점수=91, 예측점수=94
공부한 시간 =8, 실제점수=97, 예측점수=100
rmse 최종값 :3.3166247903554


#### 오차 수정 - 경사하강법(gradient decent)