In [1]:
a = np.array([[1,2],[3,4],[5,6]])

In [2]:
print(a.shape)

(3, 2)


In [3]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a.reshape(2,-1)   #나머지는 몇개인지 모르겠다 -> -1 쓰면 됨

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = np.array([
    [1,2,3,4],
    [3,4,5,6],
    [5,6,7,8]])

In [9]:
b.shape

(3, 4)

In [10]:
b = np.array([
    [[1,2],[3,4]],
    [[3,4],[5,6]],
    [[5,6],[7,8]]])

In [11]:
b.shape

(3, 2, 2)

In [12]:
b.reshape(2,-1)

array([[1, 2, 3, 4, 3, 4],
       [5, 6, 5, 6, 7, 8]])

In [13]:
a,b=(7,3)      #위 표현이 더 좋아보여
print(a)
print(b)

c=(7,3)
print(c[0])
print(c[1])

7
3
7
3


In [14]:
np.max([1,2,3,4,1,8,2.4])

8.0

In [15]:
np.argmax([1,2,3,4,1,8,2.4])  #최댓값에 해당하는 index

5

In [16]:
np.argmax([0,0,0,0,1,0])    #one-hot encoding

4

In [18]:
np.argmax([0,0,0,1,1,0])

3

In [20]:
label = [0,0,2,1]
x = np.array([[1,0,0],[1,0,0],[0,0,1],[0,1,0]])
#to_categorical 함수: label to one-hot encoding
#반대는 argmax 가 그 역할 해줌

In [21]:
np.argmax(x)

0

In [22]:
np.argmax(x,axis=1)  #axis: 0:, 1:row sum, col sum

array([0, 0, 2, 1], dtype=int64)

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
b = a.reshape(3,2,1)  #reshape 시 중요한 건 당연히 개수가 같아야지
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2, 1)


In [4]:
b[:,:,0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
b[:,:,:]

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])